// ==========================================
// THPS CORE WIDGET: CALENDAR GRID & LOBBY
// Handles Firebase Auth, Firestore Data, and the 100-Day Grid
// ==========================================

class ThpsCalendarGrid extends HTMLElement {
    async connectedCallback() {
        this.innerHTML = `
            <div class="w-full max-w-6xl mx-auto flex flex-col items-center">
                <div class="w-full flex flex-col items-center mb-8 px-2">
                    <div class="flex flex-col items-center gap-1 text-center mb-6">
                        <h1 class="text-4xl md:text-5xl uppercase tracking-wider text-slate-900" style="font-family: 'Permanent Marker', cursive;">
                            Members Hub
                        </h1>
                        <p class="text-xs md:text-sm text-slate-500 font-medium max-w-md mt-1">
                            Welcome back. Track your Daily Mic-Check progress below.<br>
                            <strong>(Score 8.5 or more to boost your Star Count!)</strong>
                        </p>
                        <div id="db-status" class="mt-2 text-[10px] font-bold px-3 py-1 bg-amber-100 text-amber-700 rounded-full animate-pulse">Connecting to Save Data...</div>
                    </div>

                    <!-- Gamification Score Panels -->
                    <div class="flex justify-center gap-4 md:gap-12 w-full">
                        <div class="flex flex-col items-center bg-gradient-to-b from-yellow-50 to-amber-100 border border-amber-200 rounded-2xl p-3 shadow-sm w-36 md:w-44 transition-all hover:scale-105 hover:shadow-md">
                            <span class="text-[10px] md:text-xs font-black uppercase tracking-widest text-amber-700 text-center mb-1 leading-tight">Golden<br>Mic-Checks</span>
                            <span id="golden-count" class="text-3xl md:text-4xl font-black text-amber-600 drop-shadow-sm">0</span>
                        </div>

                        <div class="flex flex-col items-center bg-gradient-to-b from-slate-50 to-blue-50 border border-blue-200 rounded-2xl p-3 shadow-sm w-36 md:w-44 transition-all hover:scale-105 hover:shadow-md">
                            <span class="text-[10px] md:text-xs font-black uppercase tracking-widest text-blue-700 text-center mb-1 leading-tight">Total<br>Star Count</span>
                            <div class="flex items-center gap-1">
                                <i data-lucide="star" class="w-5 h-5 md:w-6 md:h-6 text-amber-500 fill-amber-500 drop-shadow-sm"></i>
                                <span id="star-count" class="text-3xl md:text-4xl font-black text-blue-800 drop-shadow-sm">0</span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Scrollable 7-Column Grid -->
                <div class="w-full relative">
                    <div class="absolute top-0 left-0 w-full h-4 bg-gradient-to-b from-slate-50 to-transparent z-10 pointer-events-none"></div>
                    
                    <div id="grid-scroll-container" class="w-full max-h-[65vh] overflow-y-auto pb-16 pt-2 px-2 styled-scrollbar">
                        <div id="menu-grid" class="w-full grid grid-cols-2 sm:grid-cols-4 md:grid-cols-7 gap-3 md:gap-4">
                            <!-- Grid is generated by JavaScript -->
                        </div>
                    </div>
                    
                    <div class="absolute bottom-0 left-0 w-full h-12 bg-gradient-to-t from-slate-50 to-transparent z-10 pointer-events-none"></div>
                </div>
            </div>
        `;

        if (window.lucide) window.lucide.createIcons();

        this.userScores = {};
        this.currentUser = null;
        this.db = null;
        
        // Expose critical functions to the master window so the Analyzer can interact with them
        window.dbSaveScore = this.dbSaveScore.bind(this);
        window.renderMenuGrid = this.renderMenuGrid.bind(this);

        await this.initFirebase();
    }

    async initFirebase() {
        try {
            // Dynamically import Firebase ONLY when this widget is spawned!
            const { initializeApp } = await import("https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js");
            const { getAuth, signInAnonymously, onAuthStateChanged } = await import("https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js");
            const { getFirestore, doc, setDoc, collection, onSnapshot } = await import("https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js");

            const firebaseConfig = {
                apiKey: "AIzaSyBOZBkKXHQvmyhpGPBj_Ca1kaaOcS4CFm0",
                authDomain: "member-mic-check.firebaseapp.com",
                projectId: "member-mic-check",
                storageBucket: "member-mic-check.firebasestorage.app",
                messagingSenderId: "553738270562",
                appId: "1:553738270562:web:d80b87898cc836ffcdde3b",
                measurementId: "G-55L6EV735D"
            };

            const app = initializeApp(firebaseConfig);
            const auth = getAuth(app);
            this.db = getFirestore(app);
            this.setDocFn = setDoc; // Store reference for saving later
            this.docFn = doc;

            await signInAnonymously(auth);

            onAuthStateChanged(auth, (user) => {
                this.currentUser = user;
                if (user) {
                    const scoresRef = collection(this.db, 'users', user.uid, 'micCheckScores');
                    onSnapshot(scoresRef, (snapshot) => {
                        this.userScores = {};
                        snapshot.forEach(docSnap => {
                            this.userScores[docSnap.id] = docSnap.data(); 
                        });
                        this.renderMenuGrid(); 
                    }, (error) => console.error("Firestore error:", error));

                    const dbStatus = this.querySelector('#db-status');
                    dbStatus.innerText = "Progress Synchronized";
                    dbStatus.classList.replace('text-amber-700', 'text-green-700');
                    dbStatus.classList.replace('bg-amber-100', 'bg-green-100');
                    dbStatus.classList.remove('animate-pulse');
                    setTimeout(() => dbStatus.classList.add('hidden'), 3000);
                }
            });
        } catch (error) {
            console.error("Firebase init error:", error);
            this.querySelector('#db-status').innerText = "Database Connection Failed";
            this.renderMenuGrid();
        }
    }

    async dbSaveScore(dateStr, stars, score) {
        if (!this.currentUser || !this.db) return; 
        
        const existing = this.userScores[dateStr];
        let shouldSave = true;
        
        if (existing) {
            if (existing.stars > stars) shouldSave = false;
            if (existing.stars === stars && existing.score >= score) shouldSave = false;
        }

        if (shouldSave) {
            const docRef = this.docFn(this.db, 'users', this.currentUser.uid, 'micCheckScores', dateStr);
            await this.setDocFn(docRef, { stars: stars, score: score, timestamp: Date.now() });
        }
    }

    getAdelaideDateObj() {
        const formatter = new Intl.DateTimeFormat('en-US', { timeZone: 'Australia/Adelaide', year: 'numeric', month: '2-digit', day: '2-digit' });
        const parts = formatter.formatToParts(new Date());
        const year = parseInt(parts.find(p => p.type === 'year').value);
        const month = parseInt(parts.find(p => p.type === 'month').value) - 1; 
        const day = parseInt(parts.find(p => p.type === 'day').value);
        return new Date(year, month, day);
    }

    renderMenuGrid() {
        const gridEl = this.querySelector('#menu-grid');
        const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
        
        const startDate = new Date(2026, 0, 1);
        const todayObj = this.getAdelaideDateObj();
        const tomorrowObj = new Date(todayObj);
        tomorrowObj.setDate(tomorrowObj.getDate() + 1);
        
        let totalStars = 0;
        let goldenCount = 0;
        let htmlContent = '';
        
        let currentDate = new Date(startDate);
        
        while (currentDate <= tomorrowObj) {
            const yyyy = currentDate.getFullYear();
            const mm = String(currentDate.getMonth() + 1).padStart(2, '0');
            const dd = String(currentDate.getDate()).padStart(2, '0');
            const dateKey = `${yyyy}-${mm}-${dd}`;
            
            const isTomorrow = currentDate.getTime() === tomorrowObj.getTime();
            const isToday = currentDate.getTime() === todayObj.getTime();
            
            const displayStr = `${currentDate.getDate()} ${monthNames[currentDate.getMonth()]} '${String(yyyy).substring(2)}`;
            
            if (isTomorrow) {
                htmlContent += `
                    <div class="flex flex-col items-center justify-center p-3 sm:p-4 bg-slate-100 rounded-xl shadow-inner border border-slate-200 opacity-60">
                        <span class="text-xs sm:text-sm font-bold text-slate-400 mb-3">${displayStr}</span>
                        <i data-lucide="lock" class="w-5 h-5 text-slate-400 mb-2"></i>
                        <span class="text-[10px] sm:text-xs font-bold text-slate-400 uppercase tracking-widest text-center leading-tight">Check-in<br>Tomorrow</span>
                    </div>
                `;
            } else {
                const data = this.userScores[dateKey];
                let stars = 0; let score = 0.0; let scoreColor = 'text-slate-400';
                
                if (data) { 
                    stars = data.stars; 
                    score = data.score; 
                    if (score === 10) { goldenCount++; scoreColor = 'text-yellow-400 drop-shadow-md font-black'; } 
                    else if (score >= 8.5) { totalStars += stars; scoreColor = 'text-green-500'; } 
                    else if (score >= 7) { scoreColor = 'text-orange-500'; } 
                    else { scoreColor = 'text-yellow-500'; }
                }

                let starsHtml = '';
                for (let s = 1; s <= 5; s++) {
                    starsHtml += `<i data-lucide="star" class="w-2 h-2 sm:w-3 sm:h-3 ${s <= stars ? 'text-amber-500 fill-amber-500' : 'text-slate-300'}"></i>`;
                }

                const todayId = isToday ? 'id="btn-today"' : '';
                const todayRing = isToday ? 'ring-2 ring-blue-400 ring-offset-2' : '';

                // Important: window.openGameView must exist on the master HTML file!
                htmlContent += `
                    <div ${todayId} onclick="window.openGameView('${dateKey}')" class="flex flex-col items-center justify-center p-3 sm:p-4 bg-white rounded-xl shadow-sm border border-slate-200 hover:shadow-md hover:-translate-y-1 transition-all cursor-pointer group ${todayRing}">
                        <span class="text-xs sm:text-sm font-bold text-slate-700 group-hover:text-blue-600 transition-colors mb-2">${displayStr}</span>
                        <div class="flex gap-0.5 mb-1">${starsHtml}</div>
                        <span class="${scoreColor} text-lg sm:text-xl font-black">${score.toFixed(1)}</span>
                    </div>
                `;
            }
            currentDate.setDate(currentDate.getDate() + 1);
        }
        
        gridEl.innerHTML = htmlContent;
        
        this.querySelector('#star-count').innerText = totalStars;
        this.querySelector('#golden-count').innerText = goldenCount;
        if (window.lucide) window.lucide.createIcons();

        // Auto-Scroll to Today
        setTimeout(() => {
            const todayBtn = this.querySelector('#btn-today');
            const scrollContainer = this.querySelector('#grid-scroll-container');
            if (todayBtn && scrollContainer) {
                const containerRect = scrollContainer.getBoundingClientRect();
                const btnRect = todayBtn.getBoundingClientRect();
                const scrollPos = todayBtn.offsetTop - (containerRect.height / 2) + (btnRect.height / 2);
                scrollContainer.scrollTo({ top: scrollPos, behavior: 'smooth' });
            }
        }, 300);
    }
}
customElements.define('thps-calendar-grid', ThpsCalendarGrid);
